import Head from 'next/head'
import Header from '../pages/Header/'

export default function Home() {
  return (
    <div>
      <Head>
        <title>James Hyatt </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <Header />
      </header>

      <main>

      </main>

      <footer>

      </footer>

      
    </div>
  )
}
